### ISSUE TITLE
Tools page - Rom-o-Matic down

### ISSUE THREAD

**Issue by lukebarone** [networkboot/networkboot.github.com#20]
The `rom-o-matic.dev` site no longer working. I suggest it be removed.

On a side note, does anyone know of an alternative to use?

**Comment by robinsmidsrod** [comment]
I agree, if it is no longer operational it should be removed. I'm not aware of any replacement hosting of the https://github.com/xbgmsharp/ipxe-buildweb repo.

Would you be able to create a PR for this change? Remember to change the templates and not the generated files.
